"""initial 11 tables

Revision ID: df46c8b50ef1
Revises: 
Create Date: 2026-04-25 17:00:08.748517

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df46c8b50ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_codes_phone'), ['phone'], unique=False)
        batch_op.create_index('ix_sms_phone_created', ['phone', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invite_path', sa.String(length=500), nullable=True),
    sa.Column('invite_count', sa.Integer(), nullable=False),
    sa.Column('invite_earned_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='user_status_enum'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index('ix_users_invite_path', ['invite_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index('ix_users_status_created', ['status', 'created_at'], unique=False)

    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbols_count', sa.Integer(), nullable=False),
    sa.Column('total_points_charged', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'partial_done', 'done', 'failed', name='job_status_enum'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_jobs_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_level_created', ['level', 'created_at'], unique=False)
        batch_op.create_index('ix_logs_module_created', ['module', 'created_at'], unique=False)
        batch_op.create_index('ix_logs_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.Enum('manual', 'cron', name='healthcheck_trigger_type_enum'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('market_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('run_dir', sa.String(length=255), nullable=True),
    sa.Column('analysis_type', sa.Enum('full', 'quant_only', name='analysis_type_enum'), nullable=False),
    sa.Column('parent_full_result_id', sa.Integer(), nullable=True),
    sa.Column('is_cache_hit', sa.Boolean(), nullable=False),
    sa.Column('source_result_id', sa.Integer(), nullable=True),
    sa.Column('points_charged', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'refunded', name='result_status_enum'), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision_level', sa.String(length=20), nullable=True),
    sa.Column('quant_score', sa.Float(), nullable=True),
    sa.Column('trader_decision', sa.String(length=10), nullable=True),
    sa.Column('expert_scores_json', sa.JSON(), nullable=True),
    sa.Column('score_components_json', sa.JSON(), nullable=True),
    sa.Column('quant_components_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_full_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index('ix_results_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_results_symbol_created', ['symbol', 'created_at'], unique=False)
        batch_op.create_index('ix_results_type_symbol_created', ['analysis_type', 'symbol', 'created_at'], unique=False)
        batch_op.create_index('ix_results_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('invite_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_method', sa.Enum('code', 'qr', 'poster', 'link', name='invite_method_enum'), nullable=False),
    sa.Column('inviter_reward_points', sa.Integer(), nullable=False),
    sa.Column('invitee_reward_points', sa.Integer(), nullable=False),
    sa.Column('poster_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poster_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.String(length=50), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_events', schema=None) as batch_op:
        batch_op.create_index('ix_progress_result_created', ['result_id', 'created_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_quant_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_on_change', sa.Boolean(), nullable=False),
    sa.Column('notify_threshold_score_delta', sa.Integer(), nullable=False),
    sa.Column('notify_channels', sa.JSON(), nullable=True),
    sa.Column('last_quant_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_quant_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_quant_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_subscription_user_symbol')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('register_bonus', 'invite_new_user_bonus', 'invite_referrer_bonus', 'analyze_full', 'analyze_full_cache_hit', 'analyze_quant', 'refund', 'recharge', 'admin_revoke', name='transaction_reason_enum'), nullable=False),
    sa.Column('related_result_id', sa.Integer(), nullable=True),
    sa.Column('related_invite_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_invite_id'], ['invite_relations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_reason_created', ['reason', 'created_at'], unique=False)
        batch_op.create_index('ix_transactions_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('decision_change', 'score_alert', 'quant_failed', 'admin_message', name='push_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('feishu', 'dingtalk', 'email', 'site', name='push_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='push_status_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_notifications')
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_created')
        batch_op.drop_index('ix_transactions_reason_created')

    op.drop_table('point_transactions')
    op.drop_table('subscriptions')
    with op.batch_alter_table('progress_events', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_result_created')

    op.drop_table('progress_events')
    op.drop_table('invite_relations')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_user_created')
        batch_op.drop_index('ix_results_type_symbol_created')
        batch_op.drop_index('ix_results_symbol_created')
        batch_op.drop_index('ix_results_status_created')

    op.drop_table('analysis_results')
    op.drop_table('health_checks')
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_user_created')
        batch_op.drop_index('ix_logs_module_created')
        batch_op.drop_index('ix_logs_level_created')

    op.drop_table('app_logs')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_created')
        batch_op.drop_index('ix_jobs_status_created')

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_status_created')
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index('ix_users_invite_path')
        batch_op.drop_index(batch_op.f('ix_users_invite_code'))

    op.drop_table('users')
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_sms_phone_created')
        batch_op.drop_index(batch_op.f('ix_sms_codes_phone'))

    op.drop_table('sms_codes')
    # ### end Alembic commands ###
